on:
  workflow_call:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "npm"
      - name: Install Dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: SCP to server & Deploy app
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "dist/tax-report"
          target: ${{ secrets.DEPLOY_DIRECTORY }}
          rm: true # Remove target folder before upload data
          strip_components: 2